Sammy/Sammy/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'^music/', include('music.urls')),
]

Sammy/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
  # /music/
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
  # /music/album/add
  url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
  # /music/album/2
  url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
  # /music/album/2/delete
  url(r'^(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
  ]

Sammy/music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
# Red pk=1 __ an xtra column is added with a unique identifier
class Album(models.Model):
  artist = models.CharField(max_length = 250)
  album_title = models.CharField(max_length = 250)
  genre = models.CharField(max_length = 100)
  album_logo = models.CharField(max_length = 1000)
  
  def get_absolute_url(self):    #whenever you create an album, redirect to the detail view with the pk
    return reverse('music:detail', kwargs={'pk':self.pk})
	
  def __str__(self):
    return self.album_title + ' - '+ self.artist

class Song(models.Model):
  album = models.ForeignKey( Album, on_delete = models.CASCADE)  
  #	Each song is associated with an Album. Whn you delete the album, 
  # delete(CASCADE)the Songs associted
  file_type = models.CharField(max_length = 10)
  song_title = models.CharField(max_length = 250)
  is_favorite = models.BooleanField(default = False)
  def __str__(self):
    return self.song_title

Sammy/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album

class IndexView(generic.ListView):
  template_name = 'music/index.html'
  context_object_name = 'all_albums'
  
  def get_queryset(self):
    return Album.objects.all()

class DetailView(generic.DetailView):
  model = Album
  template_name = 'music/detail.html'
  
class AlbumCreate(CreateView):
  model = Album  #Create a new album
  fields = ['artist','album_title','genre','album_logo']
  
class AlbumUpdate(UpdateView):
  model = Album  #Create a new album
  fields = ['artist','album_title','genre','album_logo']
 
class AlbumDelete(DeleteView):
  model = Album
  success_url = reverse_lazy('music:index')

Sammy/music/templates/music/album_form.html
{% extends 'music/base.html '%}  
 {% block title %} Django MuziQ - Add new album{% endblock %}
 {% block albums_active %}active{% endblock %}
 {% block body %}
 <div class='container-fluid'>
 
   <div class='row col-sm-12'>
     <div class='col-sm-12 col-md-7'>
	   <div class='panel panel-default'>
	     <div class='panel-body'>
		   <form class='form-horizontal' action="" method="post" enctype='multipart/form-data'>
		     {% csrf_token %}
			 {% include 'music/form-template.html' %}
			 <div class='form-group'>
			   <div class='col-sm-offset-2 col-sm-10'>
			     <button type='submit' class='btn btn-success'>Submit</button>
			   </div>
			 </div>
		   </form>
		 </div>
	   </div>
	 </div>
   </div>
 </div>
 {% endblock %}

Sammy/music/templates/music/base.html
<!DOCTYPE html>
<html lang='en'>
  <head>
	<meta charset="UTF-8">
	<title> {% block title %} Django MuziQ {% endblock %}</title>
	{% load staticfiles %}
	<!--
	  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	  -->
	  <!--
	  <link rel="stylesheet" href="{% static 'music/bootstrap-3.3.5-dist/css/bootstrap.min.css' %}">
	  <link rel="stylesheet" href="{% static 'music/bootstrap-3.3.5-dist/css/bootstrap-theme.css' %}">
	  <script src="{% static 'music/bootstrap-3.3.5-dist/js/bootstrap.min.js' %}"></script>
	  <script src ="{% static 'music/JQuery/jquery-lib/jquery-2.1.4.min.js' %}"></script>
	  -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	  <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
	  <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
	  <!-- <script src="jquery">
	  <script src="bootstrapjs">  -->
    </head>
    <body>
	  <nav class="navbar navbar-inverse">
		 <div class='container-fluid'>
			<!-- Header -->
			   <div class='navbar-header'>
				 <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#topNavbar'>
				   <span class='icon-bar'></span>
				   <span class='icon-bar'></span>
				   <span class='icon-bar'></span>
				 </button>
				 <a class='navbar-brand' href="{% url 'music:index' %}"> Django Muziq </a>  
			  </div>
			   <!--Items -->
			   
				<div class='collapse navbar-collapse' id='topNavbar'>
				  <ul class="nav navbar-nav">
					<li class="active">
					  <a href="{% url 'music:index' %}">
						<span class='glyphicon glyphicon-cd' aria-hidden="true"></span>&nbsp; Albums
					  </a>
					</li>

					<li class="">
					  <a href="#">
						<span class='glyphicon glyphicon-music' aria-hidden="true"></span>&nbsp; Songs
					  </a>
					</li>
				  </ul>

				   <form class='navbar-form navbar-left' role="search" method="get" action="#">
					  <div class="form-group">
						<input type="text" class="form-control" name="q" value="">
					  </div>
					   <button type="button" class="btn btn-default">Search</button>
				   </form>
				   <ul class="nav navbar-nav navbar-right">
					  <li class="">
						<a href="{% url 'music:album-add'%}">
							<span class='glyphicon glyphicon-plus' aria-hidden="true"></span>&nbsp; Add Album
						</a>
					  </li>
					  <li class="">
						<a href="#">
							<span class='glyphicon glyphicon-off' aria-hidden="true"></span>&nbsp; Logout
						</a>
					  </li>

				   </ul>
				</div>
			   <!--Items -->
			   
			<!-- Header -->   
		</div>
     </nav>

  {% block body %}  
  {% endblock %}
  </body>

  </html>

Sammy/music/templates/music/detail.html
{% extends 'music/base.html '%}  
 {% block title %} Django MuziQ - Album Details{% endblock %}
 {% block body %}
  <div class="row col-sm-12">
    <div class="col-sm-4">
		<img src="{{ album.album_logo }}" height='150px' width='150px'>

		<h1> {{ album.album_title }}</h1>
		<h3>{{ album.artist }}</h3>
    </div>
	<div class="row col-sm-8">
	    <div class="row col-sm-12">
		  <button type="button" class="btn btn-primary btn-sm">View All</button>
          <button type="button" class="btn btn-default btn-sm">Add new song</button>		  
		</div>
		<div class="row col-sm-12">
		<table class="table">
         <thead>
          <tr>
            <th>Title</th>
            <th>Audio File</th>
            <th>Favorite</th>
            <th>Actions</th>
          </tr>
         </thead>
		 <tbody>
		  {% for song in album.song_set.all %} 
		   <tr>
		    <td>
			  {{song.song_title}}
			</td>
			<td>
			</td>
			<td>
			  {% if song.is_favorite %}
				<img src='http://i.imgur.com/b9b13Rd.png' />
			  {% endif %}
			</td>
            <td>
            </td>			
			</tr>
		  {% endfor %}
		 </tbody>
		</table>
		</div>
	</div>	  
   </div>
 {% endblock %}
 

Sammy/music/templates/music/form-template.html
{% for field in form %}
 <div class='form-group'>
    <div class='col-sm-offset-2 col-sm-10'>
	  <span class='text-danger small'>{{ field.errors }} </span>
	</div>
	 <label class='control-label col-sm-2'>{{ field.label_tag }}</label>
	 <div class='col-sm-10'>{{ field }}</div>
 </div>
{% endfor %}

Sammy/music/templates/music/index.html
{% extends 'music/base.html '%}  
 {% block body %}
	<div class="row col-sm-12">
	  {% for album in all_albums %}
	    
		<div class="col-sm-4"> 
	     <img src="{{ album.album_logo }}" height='150px' width='150px'> <br>
		 <h2><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a> </h2> <br>
		  <div class="row col-sm-12">
		  <form action="{% url 'music:album-delete' album.id%}" method='post' style='display: inline;'>
		    {% csrf_token %}
				<input type="hidden" name="album_id" value="{{ album.id }}"/>
			   <button type="button" class="btn btn-primary btn-sm">Show Details</button>
			   <button type="submit" class="btn btn-default btn-sm">
			      <span class="glyphicon glyphicon-trash"></span>
			   </button>
           </form>		   
		   <a href='#' class="btn btn-default btn-sm btn-favorite">
		       <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
		    </a>
		  </div>
	    </div>
		
	  {% endfor %}
	</div>
 {% endblock %}
 
 